# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fa2ad54b9166c332707165a265da7f9f621f7b2ec7237c28c3d14719b2fc164df4e8a3aa3683673ae61cd51914d83ee4ea3af5306275e8502bdda6a2b40e2803

test:
  secret_key_base: 93d44eaad5c5fa6102c6a1ebb903a5939defa2a8ce8f747400ccbbcd92332eaa21c9e24bfa6c5779ea1144413926056e597a345d85d9672be798b7d5b5338d03

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
